ACCESO-A-DATOS/SEGUNDA/Code/Respaldos/ExamenJGT/ExamenJGT/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExamenJGT.Models
{
    public class Pedido
    {
        public int ID { get; set; }
        public string NumeroPedido { get; set; }
        public DateTime FechaExpedicion { get; set; }
        public int ClienteID { get; set; }
        public Cliente Cliente { get; set; }
    }
}

ACCESO-A-DATOS/SEGUNDA/Code/Respaldos/ExamenJGT/ExamenJGT/Controllers/DetalleController.cs
using ExamenJGT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamenJGT.Controllers
{
    public class DetalleController : Controller
    {
        Contexto BD = new Contexto();

        // GET: Detalle
        public ActionResult Index()
        {
            return View();
        }

        // GET: Detalle/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        private void meterDetalleSiNoExiste(int id)
        {
            Detalle Rescatado = BD.Detalles.Find(id);
            if (Rescatado == null)
            {
                // Creo Detalle linkado al pedido
                Detalle Detalle = new Detalle() { PedidoID = id };
                // Lo inserto en la base de datos para poder encontrarl o leugo
                BD.Detalles.Add(Detalle);
                BD.SaveChanges();
            }
        }

        // GET: Detalle/Create
        public ActionResult Create(int PedidoID = 0)
        {
            // ESTO ES PARA METER LOS PRODUCTOS

            meterDetalleSiNoExiste(PedidoID);

            Detalle Detalle = BD.Detalles.Find(PedidoID); // Nunca sera null porque si no exite lo he metido antes

            // Lo paso en el viewbag
            ViewBag.DetalleID = Detalle;

            // Cargo los datos de los productos
            ViewBag.ProductosIDs = new SelectList(BD.Productos, "ID", "Nombre");

            // ESTO ES PARA LISTAR las cosas del que hay
            List<int> TodasLasComprar = new List<int>();

            List<int> productos = BD.ProductosDetalles.Where(e => e.DetalleID == Detalle.ID).Select(e => e.ProductoID).ToList();
            Detalle.ProductosDetallesIDs = productos;
            
           // NO me da tiempo de seguir

            La idea es asignar las listas con las consultas que he hecho todo el rato
                y asignar el precio al rescarte de la cantidad por el precio que tambien resctao

        }

        // POST: Detalle/Create
        [HttpPost]
        public ActionResult Create(ProductosDetalle Datos)
        {
            try
            {
                BD.ProductosDetalles.Add(Datos);
                BD.SaveChanges();
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        // GET: Detalle/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Detalle/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Detalle/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Detalle/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ACCESO-A-DATOS/SEGUNDA/Code/Respaldos/ExamenJGT/ExamenJGT/Controllers/PedidoController.cs
using ExamenJGT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamenJGT.Controllers
{
    public class PedidoController : Controller
    {
        Contexto BD = new Contexto();

        // GET: Pedido
        public ActionResult Index()
        {
            return View(BD.Pedidos.ToList());
        }

        // GET: Pedido/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Pedido/Create
        public ActionResult Create()
        {
            ViewBag.PedidosExistentes = BD.Pedidos.OrderByDescending(e => e.FechaExpedicion).ToList();
            ViewBag.ClienteID = new SelectList(BD.Clientes.ToList(), "ID", "Nombre");
            return View();
        }

        // POST: Pedido/Create
        [HttpPost]
        public ActionResult Create(Pedido Pedido)
        {
            try
            {
                //Pedido.NumeroPedido = Pedido.FechaExpedicion.Year + "-" + Pedido.ID;
                // No genera la ID hasta que mete parece ser, porque siempre lee0
                int idSBT = BD.Pedidos.ToList().Count;
                Pedido.NumeroPedido = Pedido.FechaExpedicion.Year + "-" + idSBT;
                BD.Pedidos.Add(Pedido);
                BD.SaveChanges();
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pedido/Edit/5
        public ActionResult Edit(int id)
        {
            Pedido Editando = BD.Pedidos.Find(id);
            ViewBag.ClienteID = new SelectList(BD.Clientes.ToList(), "ID", "Nombre");
            return View(Editando);
        }

        // POST: Pedido/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Pedido Insertado)
        {
            try
            {
                Pedido Editar = BD.Pedidos.Find(id);
                Editar.ClienteID = Insertado.ClienteID;
                Editar.FechaExpedicion = Insertado.FechaExpedicion;
                Editar.NumeroPedido = Insertado.NumeroPedido;
                BD.SaveChanges();
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pedido/Delete/5
        public ActionResult Delete(int id)
        {
            Pedido Borrando = BD.Pedidos.Find(id);
            ViewBag.Clientes = BD.Clientes.ToList(); // para mostrar algun datillo
            return View(Borrando);
        }

        // POST: Pedido/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Pedido Pedido)
        {
            try
            {
                Pedido Borrar = BD.Pedidos.Find(id);
                BD.Pedidos.Remove(Borrar);
                BD.SaveChanges();
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }
    }
}

ACCESO-A-DATOS/SEGUNDA/Code/Respaldos/ExamenJGT/ExamenJGT/Views/Pedido/Create.cshtml
@model ExamenJGT.Models.Pedido

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FechaExpedicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaExpedicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaExpedicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteID, "ClienteID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<table>
    <thead>
        <tr>
            <th>Numero Pedido</th>
            <th>FECHA</th>
            <th>Cliente</th>
            <th>Detalle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.PedidosExistentes)
        {
            <tr>
                <td>
                    @item.NumeroPedido
                </td>
                <td>
                    @item.FechaExpedicion
                </td>
                <td>
                    @item.Cliente.Nombre
                </td>
                <td>
                    <!-- no funciona -->
                    @*@Html.ActionLink("Create", "Create", "Detalle", new { PedidoID = item.ID }, null)*@ 
                    <a href="/Detalle/Create/?PedidoID=" + @item.ID>Detalles</a>
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    @Html.ActionLink("Back to List", "Create")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ACCESO-A-DATOS/SEGUNDA/Code/Respaldos/ExamenJGT/ExamenJGT/Views/Pedido/Delete.cshtml
@model ExamenJGT.Models.Pedido

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.CIF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.CIF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroPedido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroPedido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaExpedicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaExpedicion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Create")
        </div>
    }
</div>

ACCESO-A-DATOS/SEGUNDA/Code/Respaldos/ExamenJGT/ExamenJGT/Views/Pedido/Edit.cshtml
@model ExamenJGT.Models.Pedido

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroPedido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroPedido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroPedido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaExpedicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaExpedicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaExpedicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteID, "ClienteID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Create")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ACCESO-A-DATOS/SEGUNDA/Code/Respaldos/ExamenJGT/ExamenJGT/Views/Pedido/Index.cshtml
@model IEnumerable<ExamenJGT.Models.Pedido>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<a href="/Pedido/Create">SI SE ME HA OLVIDADO REDERIGIR ALGUN MAPEO, IR AQUÍ: PEDIDOS</a>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cliente.CIF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaExpedicion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.CIF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaExpedicion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>